// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  SUPABASE_URL: string;
  SUPABASE_PUBLISHABLE_KEY: string;
  DISPLAY_AD_ID: string;
  REWARD_AD_ID: string;
  DISPLAY_AD_DEV_ID: string;
  REWARD_AD_DEV_ID: string;
  SENTRY_DSN: string;
  SENTRY_ENABLE_IN_DEV: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
