// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _LoadingRoute } from '../pages/loading';
import { Route as _ResultRoute } from '../pages/result';
import { Route as _SuggestionRoute } from '../pages/suggestion';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/loading': (typeof _LoadingRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
    '/suggestion': (typeof _SuggestionRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/loading': (typeof _LoadingRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
    '/suggestion': (typeof _SuggestionRoute)['_outputType'];
  }
}
